/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DB_Product.Item;
import DB_Product.RelationDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import libreria.DataBase;

/**
 *
 * @author Wauricio
 */
public class Add_Multi extends javax.swing.JPanel {
    RelationDB r;
    final Item  itm;
    DefaultListModel all = new DefaultListModel();
    DefaultListModel in = new DefaultListModel();
    final String idItem;
    public Add_Multi(RelationDB r , final String idItem , final Item itm) {
        initComponents();
        this.r=r;
        this.itm=itm;
        this.idItem=idItem;
        this.setBorder(new TitledBorder(new EmptyBorder(10, 10, 10, 10),
        r.getName()));
       /* for(String name:r.getValues().keySet()){
            all.addElement(name);
        }*/
   
        try{
            //  setValuesRelations(r.getValues());
                setValuesRelations(r.getValues()); 
            jList2.setModel(all);
             jList1.setModel(in);
        }catch(SQLException ex){
            
        }
       
    }
    
    private void setValuesRelations(Map<String, String> val)throws SQLException{
      ResultSet rts= DataBase.executeSQL(itm.getdb().getConnection(),"select * from "+r.getTable()+" where " +itm.getNameID_DB()+"="+idItem);
        Map<String,String> in = new HashMap<String, String>();
      //System.out.println("select * from "+r.getTable()+" where " +r.getIdNameMatchItem()+"="+idItem);
        while(rts.next()){
            in.put(rts.getString(r.getIdNameMatch()),itm.getNameID_DB());
        }
        for (Map.Entry<String,String> entry : r.getValues().entrySet()){
              if(in.containsKey(entry.getValue()))
                  this.in.addElement(entry.getKey());
              else 
                  this.all.addElement(entry.getKey());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        jButton1.setText(">>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("<<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2);

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(jList2.getSelectedIndex()>=0){
           try{
               String sld=jList2.getSelectedValue();
           //System.out.println("insert into "+r.getTable() +" values ("+"id"+","+ r.getValues().get(sld)+")");
           //System.out.println(r.insertRelationData(r.getValues().get(sld),idItem));
           DataBase.doSQLInsert(itm.getdb().getConnection(),itm.insertRelationData(r.getValues().get(sld),idItem , r.getIdNameMatch(),r.getTable()));
           all.remove(jList2.getSelectedIndex());
           in.addElement(sld);
           itm.getdb().getConnection().commit();
           
           }
          catch(SQLException s){
                JOptionPane.showMessageDialog(null,
                "Error : Ocurrio Un Problema Con el registro",
                "Error",
                JOptionPane.ERROR_MESSAGE);
               s.printStackTrace();
           }
           
       }
       else
       {
              JOptionPane.showMessageDialog(null,
        "WARNING : Seleciona un Elemento",
        "WARNING",
        JOptionPane.WARNING_MESSAGE);

       }     
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(jList1.getSelectedIndex()>=0){
           try{
                String sld=jList1.getSelectedValue();
                //System.out.println("insert into "+r.getTable() +" values ("+"id"+","+ r.getValues().get(sld)+")");
                //System.out.println(r.deleteRelationData(r.getValues().get(sld),idItem));
                DataBase.doSQLInsert(itm.getdb().getConnection(), itm.deleteRelationData(r.getValues().get(sld),idItem,r.getIdNameMatch(),r.getTable()));
                in.remove(jList1.getSelectedIndex());
                all.addElement(sld);
                itm.getdb().getConnection().commit();

           }
           catch(SQLException s){
               JOptionPane.showMessageDialog(null,
                "Error : Ocurrio Un Problema Con el registro",
                "Error",
                JOptionPane.ERROR_MESSAGE);
               s.printStackTrace();
           }
           
       }
       else
       {
              JOptionPane.showMessageDialog(null,
        "WARNING : Seleciona un Elemento",
        "WARNING",
        JOptionPane.WARNING_MESSAGE);

       }     
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        new AddElement_UI(itm,r.getName().toLowerCase()).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
